### ISSUE TITLE
Smiley Face Bug

### ISSUE THREAD

**Issue by ethanmac9** [ethanmac9/ChemTools#7]
Superfluous parentheses cause an element "("  to be counted making a "(: X" be displayed with a blank element.
 ![](https://cloud.githubusercontent.com/assets/14004010/18037038/b13f3af0-6d48-11e6-93a6-ca73b54c3b56.PNG)  

Without the superfluous parentheses this formula works fine!
![good](https://cloud.githubusercontent.com/assets/14004010/18037046/dc38a660-6d48-11e6-9f51-637ac9abcc48.PNG)

**Comment by ethanmac9** [comment]
Interesting, while the correct composition is displayed along with the bugs the % mass gets messed up

**Comment by ethanmac9** [comment]
Seems any touching parentheses in the formula causes  the problem to occur 

![bugged2](https://cloud.githubusercontent.com/assets/14004010/18037135/d3a02ff8-6d4a-11e6-817c-ef8de51dc817.PNG)

**Comment by Chuck8521** [comment]
The problem has to do with the current condition to trigger ionic compound recognition - it looks for one "(" and assumes that everything between that and the next ")" will be elements and numbers. It doesn't test for nested parenthesis. The problem is, having it ignore the second "(" will be easy, but having it look for and destroy a second ")" might be tougher

**Comment by Chuck8521** [comment]
Simple iteration through the String ion will get rid of the second "(", but an iteration through the whole compound will be necessary to find and fix any second ")"s. It's chemically impossible for ions to be nested [citation needed], so potentially messing with user input shouldn't be a problem.

**Comment by Chuck8521** [comment]
Issue fixed with iteration through String and ignoring misplaced parenthesis, as stated above
